const zhTeamNames: Record<string, string> = {
  Argentina: "阿根廷",
  Australia: "澳大利亚",
  Belgium: "比利时",
  Brazil: "巴西",
  Canada: "加拿大",
  Chile: "智利",
  Colombia: "哥伦比亚",
  Croatia: "克罗地亚",
  "Czech Republic": "捷克",
  Denmark: "丹麦",
  Ecuador: "厄瓜多尔",
  England: "英格兰",
  France: "法国",
  Germany: "德国",
  Ghana: "加纳",
  Iran: "伊朗",
  Italy: "意大利",
  Japan: "日本",
  Mexico: "墨西哥",
  Morocco: "摩洛哥",
  Netherlands: "荷兰",
  Panama: "巴拿马",
  Paraguay: "巴拉圭",
  Poland: "波兰",
  Portugal: "葡萄牙",
  Qatar: "卡塔尔",
  Scotland: "苏格兰",
  Senegal: "塞内加尔",
  Serbia: "塞尔维亚",
  "South Africa": "南非",
  "South Korea": "韩国",
  Spain: "西班牙",
  Switzerland: "瑞士",
  Tunisia: "突尼斯",
  Uruguay: "乌拉圭",
  USA: "美国",
  Wales: "威尔士"
};

const teamFlags: Record<string, string> = {
  Argentina: "🇦🇷",
  Australia: "🇦🇺",
  Belgium: "🇧🇪",
  Brazil: "🇧🇷",
  Canada: "🇨🇦",
  Chile: "🇨🇱",
  Colombia: "🇨🇴",
  Croatia: "🇭🇷",
  "Czech Republic": "🇨🇿",
  Denmark: "🇩🇰",
  Ecuador: "🇪🇨",
  England: "🏴",
  France: "🇫🇷",
  Germany: "🇩🇪",
  Ghana: "🇬🇭",
  Iran: "🇮🇷",
  Italy: "🇮🇹",
  Japan: "🇯🇵",
  Mexico: "🇲🇽",
  Morocco: "🇲🇦",
  Netherlands: "🇳🇱",
  Panama: "🇵🇦",
  Paraguay: "🇵🇾",
  Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Qatar: "🇶🇦",
  Scotland: "🏴",
  Senegal: "🇸🇳",
  Serbia: "🇷🇸",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  Spain: "🇪🇸",
  Switzerland: "🇨🇭",
  Tunisia: "🇹🇳",
  Uruguay: "🇺🇾",
  USA: "🇺🇸",
  Wales: "🏴"
};

export function displayTeamName(name: string) {
  const zhName = zhTeamNames[name];
  const flag = teamFlags[name];
  const displayName = zhName ? `${name} (${zhName})` : name;

  return flag ? `${flag} ${displayName}` : displayName;
}
